// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi35louyf4KHKHZKoWmi7pDRp9iVzUSTo',
    appId: '1:58549037964:web:07eff2022c87b3bb1004a9',
    messagingSenderId: '58549037964',
    projectId: 'nstarstkd-b7bcf',
    authDomain: 'nstarstkd-b7bcf.firebaseapp.com',
    storageBucket: 'nstarstkd-b7bcf.firebasestorage.app',
    measurementId: 'G-YWDWGYNWEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqYDM0lm2f1z8iJYvZ1xOxCCMQbMuhuE',
    appId: '1:58549037964:android:f60574e586ec9b791004a9',
    messagingSenderId: '58549037964',
    projectId: 'nstarstkd-b7bcf',
    storageBucket: 'nstarstkd-b7bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePNzi5iup5fQxz0Tu4Q2jUOhkrkEO6ww',
    appId: '1:58549037964:ios:208645b2f1e0a1b61004a9',
    messagingSenderId: '58549037964',
    projectId: 'nstarstkd-b7bcf',
    storageBucket: 'nstarstkd-b7bcf.firebasestorage.app',
    iosBundleId: 'com.raginee.nStarsNotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCePNzi5iup5fQxz0Tu4Q2jUOhkrkEO6ww',
    appId: '1:58549037964:ios:208645b2f1e0a1b61004a9',
    messagingSenderId: '58549037964',
    projectId: 'nstarstkd-b7bcf',
    storageBucket: 'nstarstkd-b7bcf.firebasestorage.app',
    iosBundleId: 'com.raginee.nStarsNotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi35louyf4KHKHZKoWmi7pDRp9iVzUSTo',
    appId: '1:58549037964:web:b8eb069d144b23da1004a9',
    messagingSenderId: '58549037964',
    projectId: 'nstarstkd-b7bcf',
    authDomain: 'nstarstkd-b7bcf.firebaseapp.com',
    storageBucket: 'nstarstkd-b7bcf.firebasestorage.app',
    measurementId: 'G-GB0TRK0K5H',
  );
}
